name: Release NodeJS app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3


    #We need to login so we can later push the image without issues
    - name: logging into Docker Hub
      uses: docker/login-action@v2
      with:
        username:
        password: