namee: Releas DevOps with Docker # Name of the workflow

# On a push to the branch named master
on:
  push:
    branches:
      - master

# Jobs called build runs-on ubuntu-latest
jobs:
  deploy:
  name: Deploy to GitHub Pagees
  # we are not interested in this job

  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    # Checkout to the repository
   - uses: actions/checkout@v3

  #We need to login so we can later push the image without issuees
   - name: Login to Docker Hub
     uses: docker/login-action@v2
     with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
   # Builds devopsdockeruh/docker-hy.github.io
   - name: Build and Push
      uses: docker/build-push-action@v4
      with:
       push: true
       tags: mskinner1028/express:latest
